apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStores.awsSecretsManager.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStores.awsSecretsManager.region }}
