addons-root:
  addons:

    cert-manager:
      enabled: false

    ingress-nginx:
      enabled: true
      parameters:
        - name: ingress-nginx.controller.service.type
          value: NodePort
